### ISSUE TITLE
intelephense marked TestCase contains invalid code in Laravel 6, 7, 8 

### ISSUE THREAD

**Issue by stancl** [orchestral/testbench#282] opened 2020-12-13 13:41 UTC
- Testbench Version: 6.*
- Laravel Version: 8.*
- PHP Version: any
- Database Driver & Version: any

### Description:

As I said [here](https://github.com/orchestral/testbench/issues/281#issuecomment-743805664), testbench-core received a patch release on 4.* but not 6.*

> I don't have any reason to believe your issues are related to above case.

Pretty sure that when 4.11.0 and 6.8.0 introduced the same bug, and only 4.* had the bug fixed, the bug still exists in 6.*

### Steps To Reproduce:

Create a new package for Laravel 8, require testbench, try to extend the TestCase.

**Comment by crynobone** [comment] 2020-12-13 13:47
v4.11.1 simply remove an abstract method, see https://github.com/orchestral/testbench-core/compare/v4.11.0...v4.11.1#diff-5097ecf51077a57925cfebddaf5f63a068fc7e5ba99e578249fb1ec42483810a

This method doesn't exist in Testbench Core 5 and Testbench Core 6. Again, I don't have any reason to believe your issue are related.

**Comment by stancl** [comment] 2020-12-13 13:49
Try the reproduction steps then. I had this on testbench 6.x and the only way to fix it was to constrain testbench-core to a previous tag

**Comment by crynobone** [comment] 2020-12-13 13:58
![image](https://user-images.githubusercontent.com/172966/102013960-48be1800-3d8e-11eb-83cd-5ee73ba859dc.png)

Unable to reproduce.

**Comment by stancl** [comment] 2020-12-13 14:08
Here's your abstract method: https://github.com/orchestral/testbench-core/blob/6.x/src/Concerns/HandlesDatabases.php#L39

And here's an IDE error:
![Screen Shot 2020-12-13 at 15 04 42](https://user-images.githubusercontent.com/33033094/102014101-8ef68580-3d54-11eb-81ed-5593ab015b01.png)

Under some conditions, phpunit passes. But the code is still broken.

**Comment by crynobone** [comment] 2020-12-13 14:35
Both `HandlesDatabases` and `HandlesRoutes` has the abstract method, and implemented from `HandlesAnnotations`. All the trait are loaded from `Testing` trait which shouldn't cause any issue. But I can't say the same regarding the IDE I'm not using that.

**Comment by stancl** [comment] 2020-12-13 14:50
Hmm, I see. Might be an Intelephense thing, but I believe that this error happened in phpunit too a few times. I'll let others comment if they have a reproduction repo

**Comment by blimundo** [comment] 2020-12-13 16:08
Hi @crynobone and @stancl. 

VS Code is showing this error when using TestCase, but the test is running without problem.

![Screenshot from 2020-12-13 15-07-36](https://user-images.githubusercontent.com/43821095/102017207-00cecf00-3d55-11eb-94dc-13ffe7e55f88.png)

**Comment by crynobone** [comment] 2020-12-14 00:45
@blimundo this seem to be exact issue described in https://github.com/bmewburn/vscode-intelephense/issues/1412

**Comment by crynobone** [comment] 2021-01-04 09:26
This has been fixed on bmewburn/vscode-intelephense v1.6.0

**Closed by crynobone** 2021-01-04 09:26 UTC
