### ISSUE TITLE
PHPUnit_Framework_ExpectationFailedException

### ISSUE THREAD

**Issue by a-komarev** [orchestral/testbench#116] opened 2016-04-26 01:11 UTC
When I'm trying to make fail situation in test case I've got an error.

Example of fail case:

``` php
$this->post("comments", [
    'content' => 'First comment',
])->seeJson([
    'content' => 'Haha its broken',
]);
```

I've expected to see something like this:

``` php
Unable to find JSON fragment ["content":"Haha its broken"] within [{"content":"First comment", "created_at":"2016-04-26T01:08:08+0000"}].
Failed asserting that false is true.
```

But I'm getting this error:

```
PHP Fatal error:  Method PHPUnit_Framework_ExpectationFailedException::__toString() must not throw an exception in /home/ell/.composer/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php on line 0
PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /home/ell/Development/laravel-comments/vendor/laravel/framework/src/Illuminate/Container/Container.php:752
Stack trace:
#0 /home/ell/Development/laravel-comments/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /home/ell/Development/laravel-comments/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /home/ell/Development/laravel-comments/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 /home/ell/Development/laravel-comments/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions- in /home/ell/Development/laravel-comments/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752
```

**composer.json**

``` json
"require": {
    "php": ">=5.5.9",
    "illuminate/database": "~5.1.16|~5.2.0",
},
"require-dev": {
    "phpunit/phpunit" : "~5.2",
    "fabpot/php-cs-fixer": "^1.11",
    "orchestra/testbench": "~3.2"
},
```

**Comment by a-komarev** [comment] 2016-04-26 01:13
I thought it could be related to #107

**Comment by crynobone** [comment] 2016-04-26 02:10
Nope, changes #107 would only affect you if you manually override the `resolveApplicationExceptionHandler()`. Would require more detail on this.

**Comment by a-komarev** [comment] 2016-04-26 02:16
@crynobone It's only hapenning in case of `seeJson` method usage.

**Comment by crynobone** [comment] 2016-04-26 02:21
`seeJson` is basically Laravel core code, our Testbench just handle bootstrapping Laravel and most likely this is not a bug with Testbench but a configuration issue.

**Comment by a-komarev** [comment] 2016-04-26 02:40
Hmmm... the only thing I found is a recent [thread in Laravel repo](https://github.com/laravel/laravel/pull/3725), but it isn't helping me :(

**Comment by crynobone** [comment] 2016-04-26 04:16
As a start, https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L114-L129 `post()` is not the same with https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L49-L75 `json()`.

**Comment by a-komarev** [comment] 2016-04-26 13:06
```php
$this->json('POST', 'comments', [
    'content' => 'First comment',
])->seeJson([
    'content' => 'Haha its broken',
]);
```

This will get the same result: Fatal error.

**Comment by crynobone** [comment] 2017-02-04 15:38
Closing this since I can't replicate this problem by building tests to check on this scenario.

**Closed by crynobone** 2017-02-04 15:38 UTC
Labels: need feedback
